name: Build
on: [push]

jobs:
  build:
    if: ${{ !github.event.deleted }}
    runs-on: steam-frame
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - name: Build
        run: ./build.sh
      - name: Test ARM64
        run: |
          timeout 30 python3 -B -m unittest discover -s tests
          timeout 120 cargo test --locked --release --target aarch64-unknown-linux-gnu --all-targets
          cargo clippy --locked --release --target aarch64-unknown-linux-gnu --all-targets -- -D warnings
      - name: Package and publish release
        if: startsWith(github.ref, 'refs/tags/')
        run: python3 -B scripts/package.py --publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
